### PR TITLE
Home Page New Idea

### PR DESCRIPTION
**Pull request by jhasuraj01**
# Description

- New Folder named "ui" has been created for UI contributions
- Readme file in UI folder has been added
- Guideline for uploading files in "ui" folder and preview has been added

Solves #14 

## Type of change

- [x] New Design Idea Added (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots

 Original           | New Idea
 :--------------------: |:--------------------:
 image  | image |

### CODE REVIEW

**Comment by codewithvk** [comment]
@jhasuraj01 Please put image in this format `assets/homepage/<your name>/xyz.png`

**Comment by jhasuraj01** [comment]
@codewithvk I guess we should keep UI submission and Website assets separate as those assets (images, logo) will be used in frontend and keeping everything in one place might be confusing

**Comment by jhasuraj01** [comment]
@codewithvk I Made all the suggested Changes kindly review

**Comment by codewithvk** [comment]
@jhasuraj01 don't worry it is fine.

Thanks for having contributing :)

**Pull request merged**
