### PR TITLE
Testimonial Component Created

### PR DESCRIPTION
**Pull request by Castella1313**
#60 issue solved

This is how it looks like now - 
Screenshot 2021-03-25 at 7 46 21 PM

### CODE REVIEW

**Comment by Castella1313** [comment]
@codewithvk Can you please check my PR?

**Comment by codewithvk** [comment]
@Castella1313 it's  LGFM :)
here are some changes. 
increase gap between mission and testimonial
Increase the size of the testimonial. You can see sample in Issue:)

**Comment by Castella1313** [comment]
@codewithvk Done

**Comment by codewithvk** [comment]
@Castella1313 LGFM :)

**Comment by codewithvk** [comment]
@Castella1313 Apologies for my mistake, 

Could you please make a new pr with some of these changes?
1) Fetch data from the repo and create structure accordingly.
2) On every page width and height make sure `100%`.otherwise, it not comfortable with other pages.

Thanks!

**Comment by Castella1313** [comment]
@codewithvk I am just wondering how is this happening, the width is already 100% and height is auto.
Screenshot 2021-03-26 at 12 49 47 PM

**Comment by codewithvk** [comment]
> Chrome and Saf

Then go ahead with it. It might happen because I switch 17-inch display device recently. You can make pr, I will cross-check with other mentors :)

**Pull request merged**
