### PR TITLE
login Component created and route added to Navbar

### PR DESCRIPTION
**Pull request by Castella1313**
#81 issue solved

Screenshot 2021-04-07 at 7 24 35 PM

Screenshot 2021-04-07 at 7 25 51 PM

### CODE REVIEW

**Comment by Castella1313** [comment]
@codewithvk Please check my PR??

**Comment by codewithvk** [comment]
@Castella1313 Can you more improve the design part? If not then let me know I will suggest you to design.

**Comment by Castella1313** [comment]
@codewithvk yes please

**Comment by Castella1313** [comment]
@codewithvk I have modified the design 😅 Can you please check it out?


This is how it looks now - 

Screenshot 2021-04-08 at 7 17 18 PM

**Comment by codewithvk** [comment]
@Castella1313 It's looking better but wait for the design which is given by Admin. I will surely assign you for Login Page :)

**Comment by Castella1313** [comment]
@codewithvk levels aren't mentioned 😅

**Pull request merged**
